### ISSUE TITLE
Pull changes from op-otterscan in order to minimize the difference between forks

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1253]
Ours frens from test-in-prod produced op-otterscan, which is the optimism-enabled version of ots suitable to work with op-erigon.

Their repo is: https://github.com/testinprod-io/otterscan/tree/op-erigon

This is an umbrella issue, we should try to pull their changes into Otterscan in order to minimize maintenance.

There may be changes that could be turned into parameters in Otterscan, others (like op-branded logo) could maybe be turned into a branding build time parameter, or a build time override (put a new logo in some specific place and it'll override the default one, for example).

Open to discuss all of it separately in smaller issues/PRs, also we don't need to do all of it at once, we can gradually evaluate smaller changes and link them here.

**Comment by sealer3** [comment]
Differences between op-otterscan and otterscan that are general enough for this repo:
* Add `VITE_ASSETS_URL` config override environment variable
* Custom title ("Optimistic Otterscan") applied to Home, Header, and Logo
  * All three of these locations access the config via useContext anyway, so the custom title could just become a config property
* Extra chain ID to name mappings applied to WarningHeader.tsx
* Hiding extra links on the home page (e.g. EIP-1559 page link, experimental contract browser)

Other general changes:
* Moving Otterscan logo to a CDN. This is no longer necessary since the logo is now 3 KB thanks to the webp format and compression.

**Comment by wmitsuda** [comment]
I think a way to override the default logo (even if it is an instruction in the docs on which file to override 😅) should be provided, given they use a custom one, see: https://otterscan.mainnet.testinprod.io/

**Comment by sealer3** [comment]
Sure, I can add instructions for replacing the logo to the customization section of the docs.

**Comment by wmitsuda** [comment]
I think there are still some minor differences with op-otterscan, one that I remember is regarding some fields in tx details, see screenshot:

<img width="851" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/9d4cc5e9-37f4-4391-8268-21c2db86427c">

**Comment by wmitsuda** [comment]
reopening this issue since it got closed automatically by some merge.
