### ISSUE TITLE
Improve user feedback by showing an info msg when there is no public view methods on read contract page

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1330]
Try: 0x044A97AC566F348B9f229601F1240E5d1758013A on mainnet. it was failing already on 2.0.0, so not a regression.

<img width="649" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/c6a4bacd-31b7-4db7-9f34-4e0b51bfff22">

**Comment by sealer3** [comment]
@wmitsuda I am not able to reproduce this. It appears as an empty page, since the proxy ABI itself doesn't expose any view functions:

![image](https://github.com/otterscan/otterscan/assets/125761775/c71f394b-98ef-44a7-86c1-c497407eb73b)

That error seems to be a Chrome + possibly macOS related bug: https://github.com/BuilderIO/qwik/issues/5213

It affected Metamask, so it might be one of your browser extensions: https://github.com/MetaMask/metamask-extension/issues/20847 Before I do a deep dive into this, could you try disabling your extensions and explain what else happens to the Otterscan UI? It might not actually be an error that affects the UI.

**Comment by wmitsuda** [comment]
I think I now understand better what happened:

- The contract loaded correctly, I saw a bunch of methods in the contract tab (assumed it loaded correctly from Sourcify), but I didn't pay attention there were no view methods.
- I opened the "read contract" tab and because there was nothing there I assumed it was a bug and tried to find something in console.
- I saw that non-related error and assumed it was because of that nothing was displayed 🤦‍♂️

Disabling metamask made the error log disappear, so it was a false alarm.

So there is no bug here, but I think we should then improve the user feedback by displaying some info message like "No public view methods found" or something better instead of a blank page.
