### ISSUE TITLE
Decrease horizontal margin on mobile layout

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#1420]
Let's reduce the global horizontal margin by half on smaller screens in order to better use the scarce screen space.

See below a screenshot on a iPad.

A little unrelated, but I think we should also remove the entire ETH price/gas box on smaller screens because it is causing a layout break and I really don't know where to put it.

Related to #1252 

![image](https://github.com/otterscan/otterscan/assets/28685/8b72e32a-7661-4923-997c-14f854b97092)

**Comment by wmitsuda** [comment]
I just tested it on real devices, so reopening for small adjustments:

1 - I think we can shave 1 more pixel on small devices.

2 - can we make the search box fill out all the available horizontal space? See screenshot:

![Screenshot_20231027-075657](https://github.com/otterscan/otterscan/assets/28685/757c5aaf-3532-44a7-a15f-920fe693eab7)

That was taken from my phone, I'll now check on my tablet.

**Comment by wmitsuda** [comment]
interestingly, I see no effect on iPad Pro. more interestingly, google searching the resolution, it’s quite high, more than the 2xl breakpoint.

I wonder what if we use the orientation (portrait/landscape) instead of breakpoint?

<img width="834" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/3d6b0a3a-84fd-4970-b232-f31c89e6974c">

**Comment by sealer3** [comment]
Yes, I can do both (1) and (2). "Pixel" is defined by CSS3 as 1/96th of an inch, not an actual device pixel, so the actual resolution of the device shouldn't make a difference: https://drafts.csswg.org/css-values-3/#absolute-lengths. From the screenshot, it looks like the iPad Pro's viewport width is between `md` and `lg`. The same problem exists on desktop for this width.

I'll increase the cutoff to `lg`. Alternatively, we could just hide the word "Gwei" for sub-`lg` viewport widths, and that will reduce the layout break to two lines instead of three.

**Comment by wmitsuda** [comment]
looking good on phone now

![Screenshot_20231029-065121_Original](https://github.com/otterscan/otterscan/assets/28685/a8554b7a-4ced-4ef2-9715-ee2d1ad3397f)

**Comment by wmitsuda** [comment]
it worked on iPad! can we apply the same margin reduction on lg then?

![IMG_0115](https://github.com/otterscan/otterscan/assets/28685/0d95818b-ab27-4b61-9f5f-e9e371ecc767)

**Comment by wmitsuda** [comment]
it now looks good, closing
