### ISSUE TITLE
Explore possible alternatives to the Fira Code font family in function signatures

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#1718]
In #1681 (function signatures) I thought that `font-mono` looked better than `font-code`. It might just be due to the slight difference in weight (Fira Code is lighter).

On my machine `font-mono` resolves to Liberation Mono. I think for numbers and elsewhere Fira Code is fine.

Fira Code in the function signature params:
![image](https://github.com/otterscan/otterscan/assets/125761775/88ed5256-976e-4c91-be4d-a4c1f523e39e)

Liberation Mono in the function signature params:
![image](https://github.com/otterscan/otterscan/assets/125761775/2f49d4f5-a4da-42cf-9813-5af5554b2e39)

This preference of mine is just a slight one, and I haven't tested how the monospace font looks on other devices.

**Comment by wmitsuda** [comment]
for the record: Fira Code is the one I use on VS code, so I have to say I'm a little biased about it :)

**Comment by wmitsuda** [comment]
the "issue" I see with Liberation Mono is that it seems to not be available on fontsource repo (in order to test it), and if you use `font-mono` it resolves to the OS-default monospaced font.

when I chose Fira Code, my idea was to:

1 - Select a good monospaced font, given there are better fonts out there than OS-defaults (see dozens of reviews of "best font for coding").
2 - Have the same UX for any OS/browser, so forcing a specific webfont was necessary for it.

**Comment by wmitsuda** [comment]
BTW, @sealer3 is Liberation Mono the default mono font for your OS?

**Comment by sealer3** [comment]
> BTW, @sealer3 is Liberation Mono the default mono font for your OS?

`Liberation Mono` is one of the entries in Tailwind's monospace font family, and it was the first one in the list matched by my browser: https://tailwindcss.com/docs/font-family

**Comment by wmitsuda** [comment]
for the record: open to revisit this one, but for now I think setting Fira Code explicitly (+being a web font) provides a good, consistent font across all devices/OSes.
