### ISSUE TITLE
`pages-deployment` workflow failures

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#2016]
* The `on: [push]` in the integration-deployment workflow means that the workflow will run on pushes to any branch
* Without a check that the secrets exist, this workflow will fail on Otterscan forks which don't have the secrets set up.

I recommend adding a filter so that this workflow runs only on pushes to the develop branch, and adding a secrets check to the integration-deployment workflow so that the jobs are skipped if the requisite secrets are not set.

**Comment by wmitsuda** [comment]
I did some research since I think this is a general problem for any medium-large project with lots of CI stuff and found this one: https://github.com/orgs/community/discussions/26704

would disable workflows in your fork be a satisfactory solution?

also, reading further the discussion, it looks like recent forks have to explicitly opt-in to run workflows, see: https://github.com/orgs/community/discussions/26704#discussioncomment-5268498

**Comment by sealer3** [comment]
I still think that checking if the secrets exist before starting the jobs would be the best solution. Most of the other non-deployment workflows are useful for forks, so I think disabling all workflows is unnecessary, and the deployment jobs will fail without specific secrets set. Doing the check in the workflow file would mean one less hurdle for anyone who wants to contribute.

`on: [push]` is problematic for feature branches in this repo, too, unless you'd like those to have deployments as well.
