### ISSUE TITLE
Camera component does not shutdown on close

### ISSUE THREAD

**Issue by wmitsuda** [otterscan/otterscan#2320]
- Click the QR scanner button
- press "Esc" to close it, or simply scan any valid QR code
- the component does not shutdown and keeps scanning (can confirm it because my camera light indicator stays on, also can see console logs on scan attempts)

not sure when it stopped working, but I'm almost sure it is not anything related to our UI because I did a quick test now and the parent component itself is unmount (can confirm by inspecting on chrome dev tools).

I think we need to revisit our camera component usage because:

- in the past it was the only component I found to work well
- it ended up not being maintained anymore, but at that time I found out it was just some dependency issue, so I made a quick and dirty fork from the original code and updated the react dependency version.
- at that time I'm 100% it used to work.
- maybe some recent changes on react 18 (concurrency rendering, etc, etc) definitely broke it.

so we can:

- try to fix the component ourselves
- find another camera component
- investigate if something in our code is actually missing and broke the component shutdown

**Comment by wmitsuda** [comment]
worst case scenario, we can consider dropping the camera scanner support due to the lack of a decent, maintained component.

**Comment by wmitsuda** [comment]
FYI: the forked component with my changes is here: https://github.com/wmitsuda/react-qr-reader

**Comment by sealer3** [comment]
The issue has to do with the component being loaded twice in quick succession, due to React strict mode as I think you mentioned before. The first version of the component is quickly loaded and unloaded. I've identified a race condition where the cleanup function is run before the setup Promise is resolved, meaning that the scanner does not get stopped.

I'm able to get the QR scanner to stop correctly when it unloads, but the difficult thing is the unloading/loading conflicts with the video element. So I have a situation where the component unloads while the QR scanner asynchronously is still using the video element, and when the component loads again, it does not have access to the video element, which is still in use. So the second component load has no video and the QR scanner appears to be empty.

**Comment by wmitsuda** [comment]
oh wait, does that mean the issue doesn't happen in the production build?

**Comment by sealer3** [comment]
Yes, in normal usage you will not see it in the production build. That said, I am able to trigger the race condition in the production build by very quickly opening and closing the QR scanner before it can complete setup of the video stream.

**Comment by wmitsuda** [comment]
ok, so not sooo bad, but still worth investigating
