### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by 0x090909** [otterscan/otterscan#280]
Is there any way to enable dark mode?

**Comment by wmitsuda** [comment]
it needs to be implemented :)

PRs welcome, I'm not a designer, so finding good colors is really hard, also code needs to be parameterized (tailwindcss has support for it, but still need to enable and retrofit existing code)

**Comment by experimentalperson** [comment]
I think I have found good colors for dark mode I can provide them here

**Comment by experimentalperson** [comment]
Header bg color: #181a1b
Page bg color: #1e2022

Page title bg color: #85817d
Table bg color: #181a1b

Search bar bg color: #3b3b3b
Search bar suggestion text color: #686662
Search button color: #1e2022
Search button text color: #78736a

**Comment by wmitsuda** [comment]
are you interested in submitting a PR?

right now I'm busy working on new indexers, but if you are interested in working with the UI code I can help giving some pointers.

**Comment by experimentalperson** [comment]
Okay, if you point me on where do I need to introduce parametrization with tailwind I can do that

**Comment by wmitsuda** [comment]
hey, sorry for the delay, here are some points:

- tailwindcss dark mode docs: https://v2.tailwindcss.com/docs/dark-mode
- (we are stuck in tailwindcss V2 for now because of dependencies)
- I think for now you can rely on automatic dark mode settings from OS, which seems to be the default behavior from tailwind, then if we are able to make it work beautifully we can think about introducing some setting to turn it on/off
- Small UI elements are (mostly) componentized in this directory: https://github.com/wmitsuda/otterscan/tree/develop/src/components
- But some general pages are on /, like footers, headers, etc. I follow the "progressively extract smaller components" approach, but don't hesitate to ask here or in discord if you have difficulties trying to find where a certain component style is defined.
- feel free to refactor existing styles during the process, it might be that some are redundant/inherited from parent
