### ISSUE TITLE
Flag for experimental version?

### ISSUE THREAD

**Issue by tpalaz** [otterscan/otterscan#487]
On latest develop branch, was wondering if there's a flag to add experimental features (token balances) without modifying image? 
^^

**Comment by wmitsuda** [comment]
oh yeah, someone is watching the code on github 🎉😁

yes, there is, but it requires a new set of modifications to Erigon I haven't published yet (totally unstable, non-optimized, not final DB schema).

since I didn't want to keep another set of unpublished changes to Otterscan, I hid them behind an experimental flag and pushed it, so I can publish regular Otterscan releases in the meantime if needed.

But I hope to publish a first draft to Erigon soon.

**Comment by tpalaz** [comment]
Awesome! Really looking forward to it! Will keep my eyes on updates

**Comment by sealer3** [comment]
I think we can close this issue. For reference in case anyone stumbles upon this issue, the `experimental: true` flag can be set in the Otterscan config to enable Otterscan 2 features (ERC-20 token holdings, token transfers, contract enumeration, etc.), though a special Erigon version built from an ots2-alpha-* branch is required on the backend.

**Comment by wmitsuda** [comment]
agree
