### ISSUE TITLE
Reconsider truncate class for certain decoded parameters

### ISSUE THREAD

**Issue by sealer3** [otterscan/otterscan#722]
The `truncate` class, used in SelectionHighlighter, causes some parameters to get cut off in the decoded parameters table, the overflow replaced with an ellipsis. For instance, you cannot see an entire long `bytes` parameter because it is always cut off by this class.

There should be some way to see the entire decoded parameter. Showing the entire parameter also makes it easier to copy it to the clipboard. Maybe this is done by removing the `truncate` class from these decoded parameter rows.

**Comment by wmitsuda** [comment]
Agree. I have found very difficulty to pack more and more rich info into the addresses/params without causing the horizontal space to overflow.

One thing I'm thinking about is to experiment with hovers, so keep all truncate stuff, maybe removing/shortening some UI annotations and move them to a richer popup that shows on hover.

Haven't made a prototype yet due to other priorities, but agree that current situation is not good/UI not very scalable.
